/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package profileapp;

import javafx.application.Application;
import javafx.stage.Stage;
import profileapp.scenes.HomeScene;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.VBox;

public class App extends Application{
    @Override
    public void start(Stage stage){
        stage.setResizable(false);
        stage.setTitle("Profile App");

        Image imageIcon = new Image(getClass().getClassLoader().getResourceAsStream("image/download (1).jpeg"));
        stage.getIcons().add(imageIcon);

        VBox mainView = new VBox();
        Scene scene = new Scene(mainView, 580, 400);
        stage.setScene(scene);
        stage.show();
        
        HomeScene homeScene = new HomeScene(stage);
        homeScene.show();
    }

    public static void main(String[] args) {
        launch();
    }
}